---
title: "Figures for dros-adaptive-tracking"
author: "Sharon Greenblum"
date: "`r format(Sys.Date())`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '..')
```

```{r load_results,include=FALSE,echo=FALSE}
source("load_packages.R",local = knitr::knit_global())
source("workflow_functions.R")
source("plotting_functions.R")
source("helper_functions.R")
library(knitr);library(kableExtra)
load("~/Documents/cage_data/orchard_2014/data/results.orch14.Rdata")
load("~/Documents/cage_data/orchard_2014/data/results_loo.orch14.Rdata")
```

## Main Figures
```{r glmLOO, echo=FALSE,fig.dim = c(14, 4)}
shiftGroups=c("significant parallel shifts","significant anti-parallel shifts","shifts not significant")

make_loo_plot(medians.loo %>% mutate(shiftGroup=ifelse(p.adjust(pval.par.paired,method = "BH")<.05,ifelse(shift>0,shiftGroups[1],shiftGroups[2]),shiftGroups[3]))) +  
geom_vline(xintercept = c(1.5,2.5,3.5,4.5),color="gray",linetype="dashed") + guides(color=FALSE) 
```


## Tables

```{r sigSites, echo=FALSE, results = 'asis'}
timesegs=c("Timepoint 1 --> 2", "Timepoint 2 --> 3", "Timepoint 3 --> 4","Timepoint 4 --> 5","Timepoint 1 --> 5")

results$sigSites %>% filter(sigLevel>1) %>% 
  mutate(timeseg=factor(timesegs[comparison],timesegs)) %>%
  group_by(chrom,timeseg) %>% summarise(siteCount=n()) %>%
  spread(key="chrom",value="siteCount") %>%
  mutate_all(function(x){ifelse(is.na(x),0,x)}) %>% 
  mutate(timeseg=timesegs[timeseg]) %>%
  tibble::column_to_rownames(var = "timeseg") %>%
  kable(caption="Counts of significantly parallel sites")%>%
  kable_classic(full_width = F,html_font = "Cambria")
```

```{r clusters, echo=FALSE}
clCts=results$clusters %>% 
  mutate(timeseg=factor(timesegs[comparison],timesegs)) %>% 
  group_by(chrom,timeseg) %>% summarise(nClusters=n()) %>%
  spread(key=chrom,value=nClusters) %>% mutate(timeseg=as.character(timeseg)) %>% 
  mutate_all(function(x){ifelse(is.na(x),0,x)}) 

clCts=rbind(clCts,tibble(as.data.frame(t(as.data.frame(colSums(clCts[,-1]))))) %>% mutate(timeseg="All"))
clCts=clCts %>% mutate(All=rowSums(clCts[,-1])) %>% tibble::column_to_rownames("timeseg")

clCts %>%
  kbl(caption = "Cluster counts") %>%
  kable_classic(full_width = F,html_font = "Cambria")

```
